name: Deploy to VPS

on:
  push:
    branches: [ "remake" ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Build and Deploy
        run: |
          cd /root/web
          git fetch origin remake
          git reset --hard origin/remake
          bash scripts/deploy.sh
