name: Deploy to VPS

on:
  push:
    branches: [ "remake" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Build and Deploy
        run: |
          cd /root/web
          bash scripts/deploy.sh
